In [1]:
import tensorflow as tf

In [3]:
a = tf.fill([4],0.25)
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.25, 0.25, 0.25, 0.25], dtype=float32)>

In [6]:
a*tf.math.log(a)/tf.math.log(2.)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.5, -0.5, -0.5, -0.5], dtype=float32)>

In [7]:
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
a = tf.constant([0.1,0.1,0.1,0.7])
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.1, 0.1, 0.1, 0.7], dtype=float32)>

In [10]:
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=1.3567796>